---
_meta:
  type: "internalusers"
  config_version: 2
  
admin:
  hash: "$2y$12$SDkYt1/tantCCK5Dkgp.ieJKcfbzr419FQPUzkDiugGvFX.QdtHhm"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user"
  
ae-datastore:
  hash: "$2y$12$ZDiRVs3ejwGlAIsurnYG5OoH8z5O9hwnaOj2qSOKJb19hhRwjAC7u"
  reserved: true
  backend_roles: []
  description: "Invenio app user"
  